new action
Signed-off-by: sadath-12 <sadathsadu2002@gmail.com>

diff --git a/.github/workflows/validate-crd.yaml b/.github/workflows/validate-crd.yaml
--- a/.github/workflows/validate-crd.yaml
+++ b/.github/workflows/validate-crd.yaml
@@ -9,38 +9,27 @@ jobs:
   check-version:
     runs-on: ubuntu-22.04
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3
         with:
           fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
 
-      - name: Get changed files
+      - name: Get all changed files
         id: changed-files
-        run: |
-          if [ "${{ github.event_name }}" == 'pull_request' ]; then
-            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_ENV
-          else
-            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_ENV
-          fi
+        uses: jitterbit/get-changed-files@v1
 
       - name: Check for CRD changes and version update
         run: |
-          if echo "${{ env.changed_files }}" | grep -q 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/'; then
-            old_version=$(git show ${{ github.event.pull_request.base.sha }}:pkg/k8s/apis/cilium.io/client/crds/v1alpha1/register.go | grep 'CustomResourceDefinitionSchemaVersion' | awk -F'"' '{print $2}')
-            new_version=$(grep 'CustomResourceDefinitionSchemaVersion' pkg/k8s/apis/cilium.io/client/crds/v1alpha1/register.go | awk -F'"' '{print $2}')
+          for changed_file in ${{ steps.changed-files.outputs.all }}; do
+            if echo "$changed_file" | grep -q 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/'; then
+              if [[ "$changed_file" == *"register.go" ]]; then
+                # Logic to extract and compare version numbers
+                old_version=$(git show ${{ github.event.pull_request.base.sha }}:$changed_file | grep 'CustomResourceDefinitionSchemaVersion' | awk -F'"' '{print $2}')
+                new_version=$(grep 'CustomResourceDefinitionSchemaVersion' $changed_file | awk -F'"' '{print $2}')
 
-            if [ -z "$old_version" ]; then
-              echo "Error: Unable to retrieve the old version from the base branch."
-              exit 1
+                if [ "$old_version" == "$new_version" ]; then
+                  echo "Error: CRD version not updated in $changed_file! Please update the CustomResourceDefinitionSchemaVersion."
+                  exit 1
+                fi
+              fi
             fi
-
-            echo "Old version: $old_version"
-            echo "New version: $new_version"
-
-            if [ "$old_version" == "$new_version" ]; then
-              echo "Error: CRD version not updated! Please update the CustomResourceDefinitionSchemaVersion in register.go"
-              exit 1
-            fi
-          else
-            echo "No changes in the CRD files"
-          fi
+          done
