d
Signed-off-by: sadath-12 <sadathsadu2002@gmail.com>

diff --git a/.github/workflows/validate-crd.yaml b/.github/workflows/validate-crd.yaml
--- a/.github/workflows/validate-crd.yaml
+++ b/.github/workflows/validate-crd.yaml
@@ -24,13 +24,23 @@ jobs:
       - name: Check for CRD changes and version update
         run: |
           if echo "${{ env.changed_files }}" | grep -q 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/'; then
+            old_version=$(git show ${{ github.event.pull_request.base.sha }}:pkg/k8s/apis/cilium.io/v1alpha1/register.go | grep 'CustomResourceDefinitionSchemaVersion' | awk -F'"' '{print $2}')
             new_version=$(grep 'CustomResourceDefinitionSchemaVersion' pkg/k8s/apis/cilium.io/v1alpha1/register.go | awk -F'"' '{print $2}')
-            echo "New CRD version: $new_version"
-            if [ -z "$new_version" ]; then
-              echo "Error: CRD version not found! Please ensure the CustomResourceDefinitionSchemaVersion exists in register.go"
+
+            if [ -z "$old_version" ]; then
+              echo "Error: Unable to retrieve old version from the base branch."
+              exit 1
+            fi
+
+            echo "old_version=$old_version"
+            echo "new_version=$new_version"
+
+            if [ "$old_version" == "$new_version" ]; then
+              echo "Error: CRD version not updated! Please update the CustomResourceDefinitionSchemaVersion in register.go"
               exit 1
             fi
           else
             echo "No changes in the CRD files"
           fi
+
 
